# Generated by Django 3.2.16 on 2022-11-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='type',
            new_name='nature',
        ),
    ]
